version: '3.8'

services:
  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox/config.yml:/config/blackbox.yml
    command:
      - "--config.file=/config/blackbox.yml"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'

  go-backend:
    build: ./go-backend
    ports:
      - "8080:8080"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-buffer-size: "1m"
    networks:
      - default
      - external-access

  react-frontend:
    build: ./react-frontend
    ports:
      - "3000:80"
    depends_on:
      - go-backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - react-frontend

networks:
  default:
    name: go-prom-status-monitor_default

  external-access:   # 外部通信用
    name: external-access
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"