global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # メトリクスエンドポイントを持つターゲット用の設定
  - job_name: 'prometheus_targets'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets_metrics.json'

  # HTTPステータスのみを監視するターゲット用の設定
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets_http.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115